import tensorflow as tf

# TODO: Replace with custom model variant
#model = tf.keras.applications.MobileNetV2(input_shape=None,
#                                          include_top=True,
#                                          weights="imagenet")
model = tf.keras.applications.Xception( include_top=True,
                                        weights="imagenet",
                                        classes=1000,
                                        classifier_activation="softmax")
GERMAN_LABELS = {
    "Polaroid_camera": "eine Foto-Kamera",
    "lens_cap": "ein Objektivdeckel",
    "pedestal": "ein Sockel",
    "necklace": "eine Halskette",
    "typewriter_keyboard": "eine Schreibmaschinentastatur",
    "laptop": "ein Laptop",
    "pitcher": "ein Krug",
    "tray": "ein Tablett",
    "dishrag": "ein Abwaschtuch",
    "doormat": "eine Fußmatte",
    "binder": "ein Bindemittel",
    "pencil_box": "eine Federtasche",
    "joystick": "ein Steuergriff",
    "letter_opener": "ein Brieföffner",
    "measuring_cup": "ein Messbecher",
    "mortar": "ein Mörtel",
    "rubber_eraser": "ein  Radierer",
    "projector": "ein Projektor",
    "buckle": "eine Schnalle",
    "reel": "eine Rolle",
    "paintbrush": "ein Malpinsel",
    "ocarina": "eine Okarina",
    "bottlecap": "Flaschenverschluss",
    "syringe": "eine Spritze",
    "lotion": "eine Lotion",
    "stole": "eine Stola",
    "apron": "eine Schürze",
    "mailbag": "ein Briefbeutel",
    "perfume": "ein Parfüm",
    "sandal": "ein Parfüm",
    "flute": "eine Flöte",
    "binoculars": "ein Fernglas",
    "book_jacket": "ein Buchumschlag",
    "honeycomb": "eine Honigwabe",
    "poncho": "ein Poncho",
    "water_bottle": "eine Wasserflasche",
    "padlock": "ein Vorhängeschloss",
    "pajama": "ein Schlafanzug",
    "scale": "ein Maßstab",
    "bib": "ein Latz",
    "cassette_player": "ein Kassettenspieler",
    "kimono": "ein Kimono",
    "Windsor_tie": "eine Windsor-Krawatte",
    "ladle": "Schöpfkelle",
    "cornet": "ein Kornett",
    "punching_bag": "ein Boxsack",
    "tripod": "ein Dreifuß",
    "cellular_telephone": "ein Handy",
    "modem": "ein Modem",
    "computer_keyboard": "eine Tastatur",
    "space_bar": "eine Leertaste",
    "consomme": "eine Brühe",
    "cup": "eine Tasse",
    "espresso": "ein Espresso",
    "face_powder": "ein Gesichtspuder",
    "soap_dispenser": "ein Seifenspender",
    "sarong": "ein Sarong",
    "swimming_trunks": "eine Badehose",
    "loupe": "eine Lupe",
    "CD_player": "ein CD-Player",
    "reflex_camera": "eine Foto-Kamera",
    "lighter": "ein Feuerzeug",
    "switch": "ein Schalter",
    "crossword_puzzle": "ein Kreuzworträtsel",
    "stethoscope": "ein Stethoskop",
    "wallet": "ein Portemonnaie",
    "iPod": "ein iPod",
    "mouse": "eine Maus",
    "magnetic_compass": "ein Kompass",
    "strainer": "ein Sieb",
    "pill_bottle": "eine Pillendose",
    "handkerchief": "ein Taschentuch",
    "saltshaker": "ein Salzstreuer",
    "eggnog": "ein Eierlikör",
    "ballpoint": "ein Kugelschreiber",
    "chain": "eine Kette",
    "loudspeaker": "ein Lautsprecher",
    "remote_control": "eine Fernbedienung",
    "combination_lock": "ein Zahlenschloss",
    "thimble": "ein Fingerhut",
    "hook": "ein Haken",
    "whistle": "eine Pfeife",
    "paper_towel": "ein Papierhandtuch",
    "band_aid": "ein Pflaster",
    "beaker": "ein Messbecher",
    "bolo_tie": "eine Westernkrawatte",
    "can_opener": "ein Dosenöffner",
    "cassette": "eine Kassette",
    "cleaver": "ein Hackmesser",
    "cocktail_shaker": "ein Cocktail-Shaker",
    "envelope": "ein Umschlag",
    "harmonica": "eine Harmonika",
    "pick": "ein Zahnstocher",
    "purse": "eine Handtasche",
    "racket": "ein Schläger",
    "revolver": "ein Revolver",
    "rule": "ein Lineal",
    "safety_pin": "eine Sicherheitsnadel",
    "shower_curtain": "ein Duschvorhang",
    "spotlight": "ein Scheinwerfer",
    "stopwatch": "eine Stoppuhr",
    "sunglass": "ein Brennglas",
    "toaster": "ein Toaster",
    "toilet_seat": "eine Klobrille",
    "velvet": "measuring_cupSamt",
    "wall_clock": "eine Wanduhr",
    "windsor_tie": "eine Windsor-Krawatte",
    "notebook": "ein Notizbuch",
    "hand-held_computer": "ein Taschencomputer",
    "radio": "ein Radio",
    "shower_cap": "eine Badehaube",
    "diaper": "eine Windel",
    "studio_couch": "eine Couch",
    "polaroid_camera": "eine Polaroid-Kamera",
    "analog_clock": "eine Analoguhr",
    "sunglasses": "eine Sonnenbrille",
    "hard_disc": "eine Festplatte",
    "corkscrew": "eine Korkenzieher",
    "digital_watch": "eine Digitaluhr",
    "washer": "eine Waschmaschine",
    "pencil_sharpener": "ein Anspitzer",
    "tape_player": "ein Kassettenspieler",
    "barometer": "ein Barometer",
    "coffee_mug": "ein Kaffeebecher",
    "nematode": "ein Fadenwurm",
    "quill": "ein Federkiel",
    "hair_slide": "eine Haarspange",
    "nipple": "ein Babyflaschen-Aufsatz",
    "petri_dish": "eine Petrischale",
    "plate_rack": "ein Geschirr-Abtropfgitter",
    "vase": "eine Vase",
    "bubble": "eine Blase",
    "plastic_bag": "eine Plastiktüte",
    "lipstick": "ein Lippenstift",
    "hand_blower": "ein Handbläser"
}


def decode_label(prediction):
    #original_list = tf.keras.applications.mobilenet_v2.decode_predictions(prediction, top=3)[0]
    original_list = tf.keras.applications.xception.decode_predictions(prediction, top=3)[0]
    for i in range(0,len(original_list)):
        original_list[i] = list(original_list[i])
        original_list[i][1] = GERMAN_LABELS[original_list[i][1]] if original_list[i][1] in GERMAN_LABELS else original_list[i][1]
    return original_list #GERMAN_LABELS[original_label] if original_label in GERMAN_LABELS else original_label
