import tensorflow as tf

# TODO: Replace with custom model variant
model = tf.keras.applications.MobileNetV2(input_shape=None,
                                          include_top=True,
                                          weights="imagenet")

GERMAN_LABELS = {
    "reel": "eine Rolle",
    "cellular_telephone": "ein Handy",
    "modem": "ein Modem",
    "computer_keyboard": "eine Tastatur",
    "space_bar": "eine Leertaste",
    "consomme": "eine Brühe",
    "cup": "eine Tasse",
    "espresso": "ein Espresso",
    "face_powder": "Gesichtspuder",
    "soap_dispenser": "Seifenspender",
    "sarong": "ein Sarong",
    "swimming_trunks": "eine Badehose",
    "loupe": "eine Lupe",
    "CD_player": "ein CD-Player",
    "reflex_camera": "eine Foto-Kamera",
    "lighter": "ein Feuerzeug",
    "switch": "ein Schalter",
    "crossword_puzzle": "ein Kreuzworträtsel",
    "stethoscope": "ein Stethoskop",
    "wallet": "ein Portemonnaie",
    "iPod": "ein iPod",
    "mouse": "eine Maus",
    "magnetic_compass": "ein Kompass",
    "strainer": "ein Sieb",
    "pill_bottle": "eine Pillendose",
    "handkerchief": "ein Taschentuch",
    "saltshaker": "ein Salzstreuer",
    "eggnog": "Eierlikör",
    "ballpoint": "ein Kugelschreiber",
    "chain": "eine Kette",
    "loudspeaker": "ein Lautsprecher",
    "remote_control": "eine Fernbedienung",
    "combination_lock": "ein Zahlenschloss",
    "thimble": "ein Fingerhut",
    "hook": "ein Haken",
    "whistle": "eine Pfeife",
    "paper_towel": "ein Papierhandtuch",
    "band_aid": "ein Pflaster",
    "beaker": "ein Messbecher",
    "bolo_tie": "eine Westernkrawatte",
    "can_opener": "ein Dosenöffner",
    "cassette": "eine Kassette",
    "cleaver": "ein Hackmesser",
    "cocktail_shaker": "ein Cocktail-Shaker",
    "envelope": "ein Umschlag",
    "harmonica": "eine Harmonika",
    "pick": "ein Zahnstocher",
    "purse": "eine Handtasche",
    "racket": "ein Schläger",
    "revolver": "ein Revolver",
    "rule": "ein Lineal",
    "safety_pin": "eine Sicherheitsnadel",
    "shower_curtain": "ein Duschvorhang",
    "spotlight": "ein Scheinwerfer",
    "stopwatch": "eine Stoppuhr",
    "sunglass": "ein Brennglas",
    "toaster": "ein Toaster",
    "toilet_seat": "eine Klobrille",
    "velvet": "Samt",
    "wall_clock": "eine Wanduhr",
    "windsor_tie": "eine Windsor-Krawatte",
    "notebook": "ein Notizbuch",
    "hand-held_computer": "ein Taschencomputer",
    "radio": "ein Radio",
    "shower_cap": "eine Badehaube",
    "diaper": "eine Windel",
    "studio_couch": "eine Couch",
    "polaroid_camera": "eine Polaroid-Kamera",
    "analog_clock": "eine Analoguhr",
    "sunglasses": "eine Sonnenbrille",
    "hard_disc": "eine Festplatte",
    "corkscrew": "eine Korkenzieher",
    "digital_watch": "eine Digitaluhr",
    "washer": "eine Waschmaschine",
    "pencil_sharpener": "ein Anspitzer",
    "tape_player": "ein Kassettenspieler",
    "barometer": "ein Barometer",
    "coffee_mug": "ein Kaffeebecher",
    "nematode": "ein Fadenwurm",
    "quill": "ein Federkiel",
    "hair_slide": "eine Haarspange",
    "nipple": "ein Babyflaschen-Aufsatz",
    "petri_dish": "eine Petrischale"
}


def decode_label(prediction):
    original_label = tf.keras.applications.mobilenet_v2.decode_predictions(prediction, top=1)[0][0][1]
    return GERMAN_LABELS[original_label] if original_label in GERMAN_LABELS else original_label
