site_name: XAI Demonstrator
copyright: © 2021 The XAI Demonstrator Team
repo_url: https://github.com/xai-demonstrator/xai-demonstrator
edit_uri: edit/master

docs_dir: '.'
theme: material

plugins:
    - search
    - same-dir
    - exclude:
        glob:
          - 'README.md'
          - '**node_modules**'
          - '**frontend**'
          - 'deployment/*'
          - 'landing-page/*'
          - 'site/*'
        regex:
          # if we do not include JS, CSS, PNG, then the docs' assets are not included in the build
          - '^.*(?<!\.md)(?<!\.css)(?<!\.js)(?<!\.png)(?<!\.svg)$'

nav:
  - Home: 'index.md'
  - User Guide:
      - 'docs/user-guide/getting-started.md'
      - 'docs/user-guide/dev-setup.md'
      - 'docs/user-guide/use-cases.md'
      - 'docs/user-guide/deployment.md'
  - Use Cases:
      - Review Sentiment: 'review-sentiment/README.md'
      - Visual Inspection: 'visual-inspection/README.md'
      - Guess the Country: 'guess-the-country/README.md'
  - Experiment Tracking:
      - Introduction: 'experiment-tracker/README.md'
      - Experiment Proxy: 'experiment-tracker/experiment-proxy/README.md'
      - Data Collector: 'experiment-tracker/data-collector/README.md'
      - Instrumentation: 'common/backend-utils/xaidemo/tracking/README.md'
  - Tech Notes:
      - 'docs/tech-notes/monorepo.md'
      - 'docs/tech-notes/tech-stack.md'
      - 'docs/tech-notes/gcp.md'
  - 'docs/about.md'

markdown_extensions:
  - toc:
      permalink: '#'
  - admonition
  - fenced_code
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
