version: '3.7'

services:
  landing:
    image: ghcr.io/xai-demonstrator/landing-page-service:latest
    depends_on:
      - inspection
      - sentiment
    ports:
      - 8000:80

  sentiment:
    image: ghcr.io/xai-demonstrator/review-sentiment-service:latest
    depends_on:
      - jaeger
    expose:
      - 8000
    environment:
      - ENVIRONMENT=test
      - AGENT_HOST_NAME=jaeger

  inspection:
    image: ghcr.io/xai-demonstrator/visual-inspection-service:latest
    depends_on:
      - jaeger
    expose:
      - 8000
    environment:
      - ENVIRONMENT=test
      - AGENT_HOST_NAME=jaeger

  jaeger:
    image: jaegertracing/all-in-one
    expose:
      - 6831
    ports:
      - 16686:16686
    restart: always
