name: Guess the Country

on:
  workflow_dispatch:
  push:
    paths:
      - 'guess-the-country/**'
      - '!guess-the-country/tests/**'
      - '!guess-the-country/**.md'

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - uses: actions/cache@v3.3.1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./guess-the-country/country-backend/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          set -e
          cd ./guess-the-country/country-backend
          echo $PWD
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          set -e
          cd ./guess-the-country/country-backend
          echo $PWD
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Download model
        run: |
          set -e
          cd ./guess-the-country/country-backend
          ./download_model.sh

      - name: Run unit tests with pytest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: country-backend-unit
          COVERALLS_PARALLEL: ${{ github.ref == 'refs/heads/master' }}
        run: |
          set -e
          cd ./guess-the-country/country-backend
          echo $PWD
          export EXPERIMENT=1
          export SERVICE_NAME=test-case
          export COLLECTOR_URL=http://collector:8000
          pip install -r requirements-test.txt
          pytest -v --cov=country -m "not integration" tests/
          # when on master, pretend to be on branch x-cov-country-backend
          $COVERALLS_PARALLEL && export GITHUB_REF="refs/heads/x-cov-country-backend"
          $COVERALLS_PARALLEL && export GITHUB_HEAD_REF="x-cov-country-backend"
          coveralls --service=github --srcdir=guess-the-country/country-backend

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: actions/cache@v3.3.1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('./guess-the-country/country-frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          set -e
          cd ./guess-the-country/country-frontend/
          echo $PWD
          npm install

      - name: Run tests
        run: |
          set -e
          cd ./guess-the-country/country-frontend/
          echo $PWD
          npm run coverage

      - name: Report coverage
        if: github.ref == 'refs/heads/master'
        env:
          COVERALLS_SERVICE_NAME: github
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: country-frontend-unit
          COVERALLS_GIT_BRANCH: x-cov-country-frontend
        run: |
          set -e
          cd ./guess-the-country/country-frontend/
          echo $PWD
          npm install coveralls
          cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js


  build:
    runs-on: ubuntu-latest
    needs:
      - test-backend
      - test-frontend
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - uses: actions/cache@v3.3.1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('./guess-the-country/country-backend/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        set -e
        cd ./guess-the-country/country-backend
        echo $PWD
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download model
      run: |
        set -e
        cd ./guess-the-country/country-backend
        ./download_model.sh

    - name: Run integration tests with pytest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: country-backend-unit
        COVERALLS_PARALLEL: true
      run: |
        set -e
        cd ./guess-the-country/country-backend
        echo $PWD
        # pip install -r requirements-test.txt
        # pytest -v --cov=country -m "integration" tests/
        # when on master, pretend to be on branch x-cov-country-backend
        $COVERALLS_PARALLEL && export GITHUB_REF="refs/heads/x-cov-country-backend"
        $COVERALLS_PARALLEL && export GITHUB_HEAD_REF="x-cov-country-backend"
        # coveralls --service=github
        # coveralls --service=github --finish

    - name: Create container and publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: xai-demonstrator/guess-the-country-service
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        workdir: guess-the-country/
